### Define/Discover

# Cadence earns money mainly from product and maintenance revenue generated by its computational software, accelerated hardware, and semiconductor-IP solutions. Product and maintenance was $4,821.589M, or about 91% of FY2025 revenue; services was $475.170M. Its customers use the products to design complex semiconductors and electronic systems. Source: CDNS FY2025 Form 10-K, Note 1 and revenue discussion.
    #  Source: https://www.sec.gov/Archives/edgar/data/813672/000081367226000016/cdns-20251231.htm
# Synopsys shares the closest economics: EDA software, semiconductor IP, system verification, and related design services. Siemens EDA also sells EDA software, hardware, and services for IC and electronic-system design, verification, and manufacturing, but it is a business within the much broader Siemens AG.
# CDNS's reported annual earnings are positive: FY2025 GAAP diluted EPS was $4.06. I still need to research each candidate's September 1, 2026 closing price, annual reported diluted EPS, fiscal period, publication date, and whether its business differences make it use, qualify, or exclude.
# Question: CDNS's peer-P/E value is not yet determined because no candidate price and EPS inputs have been admitted. Once a defensible peer P/E is available, the implied CDNS price equals that P/E multiplied by CDNS's $4.06 diluted EPS. The current DCF base case is $142.83 per share; its displayed sensitivity range is $98.03 to $165.79 per share. The P/E result should be compared with that range, not mechanically averaged with it.

### Represent

# Peer Policy:
    # I'll consider public companies whose primary business includes electronic-design automation (EDA), semiconductor IP, or related engineering-design software. Candidates should sell high-value software and/or IP to semiconductor and electronic-systems customers and have positive annual reported EPS available by September 1, 2026. I will qualify differences in product mix, customer markets, company size, growth, margins, acquisition activity, and fiscal-year timing.
# Rejection Criteria:
    # I'll exclude companies whose main business is unrelated, whose EDA exposure is too small within a diversified company, or whose reported annual EPS is negative, unavailable, or not comparable.
# Information on Synopsys (SNPS) and Siemens EDA
    # 1. Synopsys (SNPS)
        # Primary-source business support: Synopsys FY2025 Form 10-K, Business section: it provides silicon-to-systems design solutions, including EDA, system verification/validation, semiconductor IP, software/hardware, and services.
        # Source: https://www.sec.gov/Archives/edgar/data/883241/000088324125000028/snps-20251031.htm
        # Important difference: Synopsys's results include the Ansys acquisition and its simulation-and-analysis business; that acquisition can affect growth, earnings, and comparability versus CDNS.
        # Annual reported diluted EPS: $8.04 GAAP for FY2025 ended October 31, 2025. The FY2025 Form 10-K was filed December 22, 2025, before September 1, 2026.
        # Source: 10-K, Consolidated Statements of Income / Note 16, Earnings per Share.

    # 2. Siemens EDA (Siemens AG parent: SIEGY)
        # Primary-source business support: Siemens's EDA page states that Siemens EDA provides EDA software, hardware, and services for the design, verification, and manufacturing of integrated circuits and electronic systems.
        # Source: https://www.siemens.com/en-us/company/electronic-design-automation/
        # Important difference: Siemens EDA is part of Siemens Digital Industries Software within diversified Siemens AG, rather than a standalone public EDA company. Siemens AG's consolidated P/E therefore may not represent EDA alone.
        # Annual reported diluted EPS: Siemens AG reported EUR 12.11 for FY2025 ended September 30, 2025. This is the parent's consolidated diluted EPS, not a standalone Siemens EDA EPS; standalone EDA EPS is unresolved.
        # Source: Siemens FY2025 Annual Report, Note 28, and key share figures.
        # Source: https://assets.new.siemens.com/siemens/assets/api/uuid%3A428ea18a-e7ab-4f93-a160-33908f1c3540/Siemens-Annual-Report-2025.pdf
        # The FY2025 results were released November 13, 2025, before September 1, 2026.
        # Source: https://press.siemens.com/global/en/pressrelease/earnings-release-and-financial-results-q4-fy-2025

### Open Sources and Make Your Decisions

# CDNS target: September 1, 2026 NASDAQ close $313.04; FY2025 GAAP diluted EPS $4.06; fiscal year ended December 31, 2025; FY2025 results published February 17, 2026. Price source: https://chartexchange.com/symbol/nasdaq-cdns/historical/ Earnings source: Cadence FY2025 Form 10-K, Consolidated Statements of Income, https://www.sec.gov/Archives/edgar/data/813672/000081367226000016/cdns-20251231.htm
# Synopsys (SNPS): September 1, 2026 NASDAQ close $414.82; FY2025 GAAP diluted EPS $8.04; fiscal year ended October 31, 2025; Form 10-K filed December 22, 2025. Price source: https://chartexchange.com/symbol/nasdaq-snps/historical/ Earnings source: Synopsys FY2025 Form 10-K, Consolidated Statements of Income and Note 16, https://www.sec.gov/Archives/edgar/data/883241/000088324125000028/snps-20251031.htm Decision: qualify and use. Synopsys has directly comparable EDA and semiconductor-IP operations, but its acquisition of Ansys adds simulation-and-analysis operations and acquisition effects that may affect the P/E comparison.
# Siemens EDA / Siemens AG (SIEGY): September 1, 2026 OTC close $160.26; Siemens AG FY2025 consolidated diluted EPS EUR 12.11; fiscal year ended September 30, 2025; FY2025 results released November 13, 2025. Price source: https://stockanalysis.com/quote/otc/SIEGY/history/ Earnings source: Siemens FY2025 Annual Report, Note 28, https://assets.new.siemens.com/siemens/assets/api/uuid%3A428ea18a-e7ab-4f93-a160-33908f1c3540/Siemens-Annual-Report-2025.pdf Decision: exclude from the P/E calculation. Siemens EDA's operating business is relevant, but Siemens AG's price and EPS cover a diversified parent and do not provide a standalone Siemens EDA P/E.


### Implement

# Only qualified Synopsys is entered into the calculator. Siemens EDA remains documented above as excluded because Siemens AG's consolidated P/E is not a standalone EDA multiple.
# Command run: python3 CDNS_PE_Comps.py
# Result: Synopsys P/E = 51.594527x. Applying that multiple directly to CDNS FY2025 GAAP diluted EPS of $4.06 produces a CDNS reference value of $209.47 per share. Because Synopsys is the only admitted peer, this is a single-peer reference, not a valuation range.
# I want a range so I'll add a second peer to the test in the future. I'm leaning towards either Keysight, CEVA, or Atrenta if they pass the rejection criteria.

"""P/E comparable-company valuation for Cadence Design Systems (CDNS).

Use the September 1, 2026 valuation date.  Add prices and annual reported
diluted EPS only after recording the source, fiscal period, and use/qualify
decision in the accompanying research notes.
"""

from __future__ import annotations

from statistics import median


TARGET = {
    "ticker": "CDNS",
    "name": "Cadence Design Systems",
    "price": 313.04,
    "diluted_eps": 4.06,
}

# Synopsys is qualified and included. Siemens EDA is excluded and retained in the source notes above.
PEERS = [
    {
        "ticker": "SNPS",
        "name": "Synopsys",
        "price": 414.82,
        "diluted_eps": 8.04,
    },
]


def peer_key(record: dict[str, object]) -> str:
    """Return a case-insensitive identity key, preferring ticker."""
    ticker = str(record.get("ticker") or "").strip().upper()
    name = str(record.get("name") or "").strip().casefold()
    return f"ticker:{ticker}" if ticker else f"name:{name}"


def valid_number(value: object) -> bool:
    """True only for numeric, positive values (excluding bool)."""
    return isinstance(value, (int, float)) and not isinstance(value, bool) and value > 0


def format_price(value: float | None) -> str:
    return "not meaningful" if value is None else f"${value:,.2f}"


def implied_price(multiple: float, target_eps: object) -> float | None:
    """Apply an equity multiple directly to EPS; no EV-to-equity bridge exists here."""
    if not valid_number(target_eps):
        return None
    return multiple * float(target_eps)


def usable_peers() -> list[dict[str, object]]:
    """Deduplicate peers, exclude the target, and attach valid P/E calculations."""
    target_key = peer_key(TARGET)
    seen: set[str] = set()
    usable: list[dict[str, object]] = []

    print("Peer screening and P/E calculations")
    for peer in PEERS:
        label = f"{peer.get('ticker', '')} — {peer.get('name', '')}".strip(" —")
        key = peer_key(peer)
        if key == target_key:
            print(f"  {label}: excluded (target)")
            continue
        if key in seen:
            print(f"  {label}: excluded (duplicate peer)")
            continue
        seen.add(key)

        price = peer.get("price")
        eps = peer.get("diluted_eps")
        if not valid_number(price) or not valid_number(eps):
            problems = []
            if not valid_number(price):
                problems.append("price missing or nonpositive")
            if not valid_number(eps):
                problems.append("diluted EPS missing or nonpositive")
            print(f"  {label}: P/E not meaningful ({'; '.join(problems)})")
            continue

        multiple = float(price) / float(eps)
        usable.append({**peer, "pe": multiple})
        print(f"  {label}: P/E = {multiple:.6f}x")
    return usable


def print_full_peer_estimate(peers: list[dict[str, object]]) -> float | None:
    """Print min/median/max P/E outputs and return the unrounded median estimate."""
    if not peers:
        print("\nNo usable peers: no P/E estimate.")
        return None

    multiples = [float(peer["pe"]) for peer in peers]
    low, middle, high = min(multiples), float(median(multiples)), max(multiples)
    target_eps = TARGET.get("diluted_eps")

    print("\nFull-peer P/E valuation")
    if not valid_number(target_eps):
        print("  Target diluted EPS is missing or nonpositive: implied prices are not meaningful.")
        return None

    if len(peers) == 1:
        print(f"  Reference P/E: {middle:.6f}x")
        print(f"  Reference implied price: {format_price(implied_price(middle, target_eps))}")
        print("  One valid peer: reference estimate only; no range.")
    else:
        print(f"  Minimum P/E: {low:.6f}x  ->  {format_price(implied_price(low, target_eps))}")
        print(f"  Median P/E:  {middle:.6f}x  ->  {format_price(implied_price(middle, target_eps))}")
        print(f"  Maximum P/E: {high:.6f}x  ->  {format_price(implied_price(high, target_eps))}")

    return implied_price(middle, target_eps)


def print_peer_removal_test(peers: list[dict[str, object]], full_estimate: float | None) -> None:
    print("\nPeer-removal test (median P/E implied price)")
    if not peers:
        print("  No usable peers: no removal estimates.")
        return
    if full_estimate is None:
        print("  Target diluted EPS is missing or nonpositive: removal estimates are not meaningful.")
        return

    for removed in peers:
        remaining = [peer for peer in peers if peer is not removed]
        label = f"{removed.get('ticker', '')} — {removed.get('name', '')}".strip(" —")
        if not remaining:
            print(f"  Remove {label}: no estimate (no usable peers remain)")
            continue
        remaining_median = float(median([float(peer["pe"]) for peer in remaining]))
        remaining_estimate = implied_price(remaining_median, TARGET.get("diluted_eps"))
        change = remaining_estimate - full_estimate  # type: ignore[operator]
        print(
            f"  Remove {label}: {format_price(remaining_estimate)} "
            f"(change from full-peer estimate: ${change:+,.2f})"
        )


def main() -> None:
    print(f"Target: {TARGET.get('ticker', '')} — {TARGET.get('name', '')}")
    if not valid_number(TARGET.get("diluted_eps")):
        print("Target diluted EPS: missing or nonpositive; implied prices will not be meaningful.")
    else:
        print(f"Target diluted EPS: ${float(TARGET['diluted_eps']):.6f}")

    peers = usable_peers()
    full_estimate = print_full_peer_estimate(peers)
    print_peer_removal_test(peers, full_estimate)


if __name__ == "__main__":
    main()



### Validate

# Synopsys' price/EPS by hand gives me $414.82 ÷ $8.04 = 51.595x P/E
# Removing a peer, Synopsys, leaves no peers, so to remove the firm gives me no useful insight.
# No price change/loss of information to be reported.



###This report was written for FIN 43900 (AI Finance Applications, Purdue) as a learning exercise. It is not investment research and it is not financial advice.

###AI assistance: drafted with [Codex], resumed from my Lab 03 session; sources gathered and verified by me; the judgments are mine.

###Any remaining errors are my own.